{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/badServerResponse"},"variants":[{"paths":["\/documentation\/mdots\/autherror\/badserverresponse"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"s:5MDots9AuthErrorO17badServerResponseyA2CmF","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badServerResponse"}],"modules":[{"name":"MDots"}],"title":"AuthError.badServerResponse"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"badServerResponse"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","title":"MDots","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/mdots","abstract":[],"images":[{"identifier":"new-icon.png","type":"icon"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError/badServerResponse":{"title":"AuthError.badServerResponse","url":"\/documentation\/mdots\/autherror\/badserverresponse","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/badServerResponse","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"badServerResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError":{"kind":"symbol","abstract":[{"type":"text","text":"An enumeration representing various authentication errors that can occur."}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError","title":"AuthError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"url":"\/documentation\/mdots\/autherror","type":"topic"},"new-icon.png":{"identifier":"new-icon.png","type":"image","alt":"The logo representing the MDot sensor application.","variants":[{"url":"\/images\/new-icon.png","traits":["1x","light"]}]}}}